token = "<insert your bot token here>"

[premade-creator]
start = "0  * * * * *"
end   = "30 * * * * *"
tick  = 1
games = [
    ["lÃ©golÃ©jande",   "ğŸ¦ˆ", "5"],
    ["overwatch",     "ğŸ”«", "6"],
    ["rocket league", "ğŸ", "3"],
]

[premade-creator.servers]
"server id" = channel id
