# @TODO Insert your token here
token = "<insert your bot token here>"

[premade-creator]
tick  = 1
games = [
    ["lÃ©golÃ©jande",   "ğŸ¦ˆ", "5"],
    ["overwatch",     "ğŸ”«", "6"],
    ["rocket league", "ğŸ", "3"],
]
