# @TODO Insert your token here
token = "<insert your bot token here>"

[premade-creator]
start = "0  * * * * *"
end   = "30 * * * * *"
tick  = 1
games = [
    ["lÃ©golÃ©jande",   "ğŸ¦ˆ", "5"],
    ["overwatch",     "ğŸ”«", "6"],
    ["rocket league", "ğŸ", "3"],
]

# @TODO Add your server id, the channel id you want to send the message in, and then the 
# roles you want to @ (optional, don't use over 2000 characters or the message won't be
# sent.)
[premade-creator.servers]
"server id" = [channel id, ...role ids]
